#pragma once

#define MASTER_LEFT
#define SPLIT_USB_DETECT
#define SPLIT_USB_TIMEOUT 5000
#define SPLIT_USB_TIMEOUT_POLL 20
#define SPLIT_WATCHDOG_ENABLE
#define SPLIT_WATCHDOG_TIMEOUT 6000

// Better settings for home row mods
#define TAPPING_TERM 225
#define PERMISSIVE_HOLD
#define CHORDAL_HOLD
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

