name: Visualize Keymap
on:
  workflow-dispatch:
  push:
    branches: [ "main", "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    steps:
      - uses: actions/checkout@v4
      - run: pip install keymap-drawer
      - run: |
          mkdir -p /qmk_firmware/keyboards/qmk-keymap
          cp -r . /qmk_firmware/keyboards/qmk-keymap
      - run: |
          qmk c2json /qmk_firmware/keyboards/qmk-keymap/keymaps/default/keymap.c | keymap parse -q - > visualize.yaml
          # keymap draw visualize.yaml > visualize.svg


