name: Visualize Keymap

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: pip install keymap-drawer
      - uses: actions/checkout@v4
        with:
          repository: qmk/qmk_firmware
          submodules: true
      - run: docker pull ghcr.io/qmk/qmk_cli
      - uses: actions/checkout@v4
        with:
          path: keyboards/totem
      - run: docker run -v .:/qmk_firmware ghcr.io/qmk/qmk_cli qmk c2json -kb totem -km default > keymap.json
      - run: keymap parse -q keymap.json > keymap.yaml
      - run: keymap draw keymap.yaml > keyboards/totem/keymap.svg
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          repository: keyboards/totem
          commit_message: "docs: auto update keymap.svg"
