# WARNING AI GENERATED SLOB BELOW


# .github/workflows/keymap.yml

name: Generate Keymap SVG

# This action runs on every push to the 'main' branch.
# You can change 'main' to your repository's default branch name (e.g., 'master').
on:
  push:
    branches:
      - main

jobs:
  generate-svg:
    # Use the latest version of Ubuntu as the runner
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository code
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up Python, which is needed for 'qmk' and 'keymap-drawer'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install the required Python packages
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install qmk keymap-drawer

      # Step 4: Run your commands to generate the keymap.yaml and keymap.svg
      # This uses the exact commands from your request.
      # It also ensures the target directory exists first.
      - name: Generate keymap visualization
        run: |
          mkdir -p visualize
          qmk c2json keymaps/default/keymap.c | keymap -c visualize/keymap-drawer-config.yaml parse -c 12 -q - > visualize/keymap.yaml
          keymap -c visualize/keymap-drawer-config.yaml draw visualize/keymap.yaml > visualize/keymap.svg

      # Step 5: Commit the newly generated keymap.svg back to your repository
      # This action automatically detects if the file has changed and creates a commit.
      - name: Commit updated SVG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: Auto-generate keymap.svg"
          # Specify the exact file to commit
          file_pattern: visualize/keymap.svg
          # Use the standard GitHub Actions bot as the author
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

