name: Generate Keymap SVG

on:
  workflow_dispatch:
  push:
    paths:
      - 'keymaps/totem/keymap.c'

jobs:
  generate-svg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Keymap Files
        run: |
          mkdir -p visualize
          docker run --rm -v ${{ github.workspace }}:/qmk -w /qmk ghcr.io/qmk/qmk_cli sh -c "qmk c2json -kb totem -km default | keymap -c visualize/keymap-drawer-config.yaml parse -c 12 -q - > visualize/keymap.yaml && keymap -c visualize/keymap-drawer-config.yaml draw visualize/keymap.yaml > visualize/keymap.svg"

      - name: Commit Files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update keymap visualization"
          file_pattern: visualize/keymap.yaml visualize/keymap.svg

